### ISSUE TITLE
Timeout loading js libraries

### ISSUE THREAD

**Issue by Stypox** [nraynaud/webgcode#32]
Sometimes when I open "https://nraynaud.github.io/webgcode/" I get a page with only some text. This is the error I get in the console (Firefox):
```
Error: Load timeout for modules: Ember,templates,libs/threejs/OrbitControls,libs/threejs/CSS3DRenderer
http://requirejs.org/docs/errors.html#timeout
```

**Comment by nraynaud** [comment]
Hi, thanks for reporting the issue.

alas, I think it's a network or server error, neither of which I have a grip on. The error is reported in an unusual way because I used require.js.

I don't think I can fix this issue.

I'll leave the issue open for a few days to see if other people want to chime in, absent any other complaint I will close it without further action.
